package com.banyuan.gui;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import com.banyuan.theClient.Client;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.temporal.ChronoUnit;
import java.util.Date;

/**
 * @author newpc
 */
public class Question extends javax.swing.JFrame {
    JFrame jFrame = new JFrame();

    /**
     * Creates new form Question
     */
    public Question() throws IOException {
        Client.getQuestions();
        initComponents();
    }

    int i = 1;
    int score = 0;
    Date endDate = new Date();
    Date d1 = null;
    long sc = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() throws IOException {
        this.setLocation(400, 300);
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        //得到题目集合


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        String[] st = new String[Client.list.size()];
        for (int i = 0; i < Client.list.size(); i++) {
            st[i] = (String) Client.list.get(i);
        }
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        // 获取当前时间
        Date startDate = new Date();
        String nowtime = df.format(startDate);
        // System.out.println(nowtime);


        try {
            d1 = df.parse(nowtime);
        } catch (ParseException e) {
            e.printStackTrace();
        }


        jTextField1.setText(1 + "." + st[0].substring(0, st[0].length() - 1));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("考试题目");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("A");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("B");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("C");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("D");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton3.setEnabled(false);
        jButton1.setText("下一题");

        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                if (jRadioButton1.isSelected()) {

                    if (jRadioButton1.getText().equals(st[i - 1].substring(st[i - 1].length() - 1))) {
                        score += 5;
                    }
                    jTextField1.setText(i + 1 + "." + st[i].substring(0, st[i].length() - 1));
                    i++;
                } else if (jRadioButton2.isSelected()) {

                    if (jRadioButton2.getText().equals(st[i - 1].substring(st[i - 1].length() - 1))) {
                        score += 5;
                    }
                    jTextField1.setText(i + 1 + "." + st[i].substring(0, st[i].length() - 1));
                    i++;

                } else if (jRadioButton3.isSelected()) {

                    if (jRadioButton3.getText().equals(st[i - 1].substring(st[i - 1].length() - 1))) {
                        score += 5;
                    }
                    jTextField1.setText(i + 1 + "." + st[i].substring(0, st[i].length() - 1));
                    i++;
                } else if (jRadioButton4.isSelected()) {
                    ;
                    if (jRadioButton4.getText().equals(st[i - 1].substring(st[i - 1].length() - 1))) {
                        score += 5;
                    }
                    jTextField1.setText(i + 1 + "." + st[i].substring(0, st[i].length() - 1));
                    i++;
                }
                if (i >= 21) {
                    jTextField1.setText("你已经做完所有题目了，期待你的成绩吧");
                    endDate = new Date();
                    String nowtime = df.format(endDate);

                    Date d2 = null;
                    try {
                        d2 = df.parse(nowtime);
                    } catch (ParseException e) {
                        e.printStackTrace();
                    }
                    // 这样得到的差值是微秒级别
                    long diff = d2.getTime() - d1.getTime();
                    //天
                    long days = diff / (1000 * 60 * 60 * 24);
                    //小时
                    long hours = (diff - days * (1000 * 60 * 60 * 24))
                            / (1000 * 60 * 60);
                    // 秒
                    sc = (diff - days * (1000 * 60 * 60 * 24) - hours
                            * (1000 * 60 * 60)) / (1000);

                    JOptionPane.showMessageDialog(jFrame, "恭喜你完成答题", "提示消息", JOptionPane.INFORMATION_MESSAGE);
                    jButton1.setEnabled(false);
                    jButton3.setEnabled(true);
                    jButton3.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent eve) {
                            JOptionPane.showMessageDialog(jFrame, "你的分数为" + score, "提示消息", JOptionPane.INFORMATION_MESSAGE);

                            try {
                                Client.dos.writeUTF("11," + score + "," + sc);
                                Client.dos.flush();
                            } catch (IOException e) {
                                e.printStackTrace();
                            }
                            dispose();
                            UpdataStuScoreResult stuSelResult = new UpdataStuScoreResult();
                            stuSelResult.setVisible(true);
                        }

                    });
                }

                System.out.println(score);
                System.out.println(st[i - 1].substring(st[i - 1].length() - 1));
                System.out.println(sc);
            }
        });


        jTextField1.setEditable(false);


        jButton2.setText("退出");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
                Student student = new Student();
                student.setVisible(true);
            }
        });

        jButton3.setText("提交");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jRadioButton1)
                                                                                        .addComponent(jRadioButton3))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jRadioButton4)
                                                                                        .addComponent(jRadioButton2)))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(127, 127, 127)
                                                                                .addComponent(jLabel1)))
                                                                .addGap(76, 76, 76))
                                                        .addComponent(jTextField1)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(jButton2)
                                                .addGap(51, 51, 51)
                                                .addComponent(jButton3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton1)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton2)
                                        .addComponent(jRadioButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioButton3)
                                        .addComponent(jRadioButton4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton2)
                                        .addComponent(jButton3))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Question().setVisible(true);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextArea jTextField1;
    // End of variables declaration
}
